### ISSUE TITLE
Использование HttpContext.Request.Items

### ISSUE THREAD

**Issue by eterekhin** [unchase/Unchase.FluentPerformanceMeter#1]
Почему вы используете Items, а не зарегистрируйте service ```PerformanceMeter``` в ```ServiceProvider```'e. Его потом можно в фильтрах через ```HttpContext.RequestServices``` доставать. Сейчас рефлексивно вызывается ```TryAddCustomData``` в методе ```OnActionExecuting```?

**Comment by unchase** [comment]
Каждому классу, у которого мы считаем производительность методов, соответствует свой `PerformanceMeter<TClass>`, где `TClass` - тип этого класса (у нас нет общего `PerformanceMeter` для всех классов).

При этом инициализация таких классов должна происходить непосредственно в момент вызова отслеживаемого метода (так реализован механизм запуска таймера: нам нужно, как минимум, имя вызываемого метода), поэтому создание экземпляра класса `PerformanceMeter<TClass>` должно быть в `OnBeforeAction`. А в методе `OnBeforeAction` недоступен `ServiceProvider`, чтобы зарегистрировать созданный `PerformanceMeter<TClass>`, как вы предлагаете, поэтому я и использую Items в качестве "контейнера".

Если я всё же неправ, то вы можете сделать PR со своими предложениями.
